# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8093140ee1efc4464b856e0ae8002ec269b517d037772be73e4b50ab98f4b4d6b3ef7dd03bebc448b47519bc64dd6b32e4e43001986687e1b9e07b16f10e15f

test:
  secret_key_base: d1b14c0f8cdabd33788091462d5fe4cce3e700158b164a726fc177b2f14fd6e8960c3ef009615f579d7b4a77f262fc4fd995859d32ccadd02e0bf52d2322b129

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
